services:
  subsonic-search:
    image: ghcr.io/pattyjogal/subsonic-jukebox-backend:latest
    container_name: subsonic-search-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
